export const themeConfig = {
  token: {
    colorTextBase: "#2a2a2a",
    colorBgBase: "#f9f9f9",
    borderRadius: 12,
    wireframe: true,
    colorPrimary: "#2e37a4",
    colorInfo: "#2e37a4",
    fontSize: 16,
  },
  components: {
    Button: {
      paddingInline: 20,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontSize: 18,
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
    },
    Typography: {
      fontFamilyCode: '"Geologica", sans-serif',
    },
    Menu: {
      algorithm: true,
      iconSize: 16,
      itemMarginInline: 16,
      itemMarginBlock: 8,
      itemBorderRadius: 8,
      groupTitleFontSize: 16,
    },
    Pagination: {
      itemSize: 40,
      itemSizeSM: 32,
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
      fontFamily: '"Geologica", sans-serif',
    },
    Cascader: {
      menuPadding: 8,
      optionPadding: "8px 12px",
    },
    DatePicker: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontFamily: '"Geologica", sans-serif',
      borderRadius: 8,
    },
    Checkbox: {
      borderRadiusSM: 4,
      fontFamily: '"Geologica", sans-serif',
      controlInteractiveSize: 18,
    },
    Form: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontFamily: '"Geologica", sans-serif',
      labelHeight: 40,
      marginLG: 32,
      marginXXS: 12,
      paddingSM: 20,
    },
    Input: {
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
    },
    InputNumber: {
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
    },
    Radio: {
      controlHeight: 40,
      dotSize: 12,
      radioSize: 20,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontFamily: '"Geologica", sans-serif',
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
    },
    Select: {
      borderRadius: 8,
      borderRadiusLG: 10,
      borderRadiusSM: 4,
      paddingXXS: 8,
      paddingXS: 12,
      paddingSM: 16,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      multipleItemHeight: 36,
      multipleItemHeightLG: 40,
      multipleItemHeightSM: 24,
      optionPadding: "8px 12px",
    },
    TreeSelect: {
      borderRadius: 8,
      fontFamily: '"Geologica", sans-serif',
      borderRadiusSM: 4,
    },
    Upload: {
      fontFamily: '"Geologica", sans-serif',
      borderRadiusLG: 8,
    },
    Calendar: {
      borderRadiusLG: 8,
      borderRadiusSM: 4,
    },
    Card: {
      borderRadiusLG: 8,
    },
    Collapse: {
      borderRadiusLG: 8,
    },
    Descriptions: {
      borderRadiusLG: 8,
    },
    Popover: {
      borderRadiusLG: 8,
    },
    Segmented: {
      borderRadius: 8,
      borderRadiusLG: 12,
      borderRadiusSM: 4,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      trackPadding: 4,
      controlPaddingHorizontal: 16,
    },
    Table: {
      borderRadius: 8,
    },
    Tabs: {
      borderRadius: 6,
      borderRadiusLG: 8,
      cardPadding: "8px 24px",
    },
    Tag: {
      lineHeightSM: 1.8,
    },
    Tooltip: {
      borderRadius: 8,
    },
    Alert: {
      borderRadiusLG: 8,
    },
    Message: {
      borderRadiusLG: 8,
      lineHeight: 1.2,
    },
    Modal: {
      borderRadiusLG: 8,
    },
    Notification: {
      borderRadiusLG: 8,
    },
    Skeleton: {
      controlHeight: 60,
    },
    Spin: {
      dotSize: 24,
    },
  },
};
